version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./kinopedia.db:/app/kinopedia.db
    environment:
      - DATABASE_URL=sqlite+aiosqlite:///./kinopedia.db